import os

lines = []
a = lines.append

a('/** FASE-4.N-P7 -- Carga masiva Bali (resto del CSV)')
a(' * Uso: npx tsx --env-file=.env.local scripts/loadBaliAll.ts')
a(' * Idempotente: SKIP si external_id ya existe o sin fotos.')
a(' * Append a scripts/output/bali-carga-log.json.')
a(' */')
a('')
a('import { createClient } from "@supabase/supabase-js"')
a('import { parse } from "csv-parse/sync"')
a('import * as fs from "fs"')
a('import * as path from "path"')
a('')
a('const supabase = createClient(')
a('  process.env.NEXT_PUBLIC_SUPABASE_URL!,')
a('  process.env.SUPABASE_SERVICE_ROLE_KEY!,')
a('  { auth: { autoRefreshToken: false, persistSession: false } }')
a(')')
a('')
a('const CSV_PATH   = path.join(__dirname, "output", "bali-carga-final.csv")')
a('const FOTOS_BASE = path.join(__dirname, "output", "bali-fotos")')
a('const LOG_PATH   = path.join(__dirname, "output", "bali-carga-log.json")')
a('')
a('function generateSlug(title: string): string {')
a('  const base = title')
a('    .toLowerCase()')
a('    .normalize("NFD")')
a('    .replace(/[\\u0300-\\u036f]/g, "")')
a('    .replace(/[^a-z0-9\\s-]/g, "")')
a('    .trim()')
a('    .replace(/\\s+/g, "-")')
a('  return base + "-" + Date.now().toString(36)')
a('}')
a('')
a('function sanitizeExt(filename: string): string {')
a('  const rawExt = filename.includes(".") ? (filename.split(".").pop() ?? "") : ""')
a('  return /^[a-zA-Z0-9]{1,5}$/.test(rawExt) ? rawExt.toLowerCase() : "jpg"')
a('}')
a('')
a('async function uploadPhoto(filePath: string): Promise<string> {')
a('  const filename    = path.basename(filePath)')
a('  const ext         = sanitizeExt(filename)')
a('  const storagePath = `properties/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`')
a('  const buffer      = fs.readFileSync(filePath)')
a('  const ct          = `image/${ext === "jpg" ? "jpeg" : ext}`')
a('  const { error }   = await supabase.storage')
a('    .from("property-images")')
a('    .upload(storagePath, buffer, { contentType: ct, upsert: true })')
a('  if (error) throw new Error(`Upload failed for ${filename}: ${error.message}`)')
a('  const { data: u } = supabase.storage.from("property-images").getPublicUrl(storagePath)')
a('  return u.publicUrl')
a('}')
a('')
a('interface CsvRow {')
a('  title_es: string; property_type: string; price: string; currency: string')
a('  location: string; bedrooms: string; bathrooms: string; area_sqm: string')
a('  external_id: string; descripcion_es: string; nota: string')
a('}')
a('')
a('interface InsertResult {')
a('  external_id: string; status: "ok" | "skip_exists" | "skip_no_photos" | "error"')
a('  reason?: string; id?: string; ref_code?: string | null')
a('  slug?: string; gallery_urls_count?: number; image_url?: string')
a('}')
a('')
a('async function main() {')
a('  console.log("================================================")')
a('  console.log("  FASE-4.N-P7 -- Carga masiva Bali")')
a('  console.log("================================================")')
a('')
a('  const rows: CsvRow[] = parse(fs.readFileSync(CSV_PATH, "utf-8"), {')
a('    columns: true, skip_empty_lines: true, trim: true,')
a('  })')
a('  console.log(`\\nCSV: ${rows.length} filas`)')
a('')
a('  const { data: existing } = await supabase')
a('    .from("properties")')
a('    .select("external_id")')
a('    .eq("external_source", "prestige-bali")')
a('  const existingIds = new Set(')
a('    (existing ?? []).map((r: { external_id: string | null }) => r.external_id).filter(Boolean)')
a('  )')
a('  console.log(`DB: ${existingIds.size} ya existen con external_source=prestige-bali`)')
a('')
a('  const results: InsertResult[] = []')
a('  let countOk = 0, countExists = 0, countNoPhotos = 0')
a('  const okRefCodes: string[] = []')
a('')
a('  for (const row of rows) {')
a('    const eid = row.external_id')
a('    console.log(`\\n--- ${eid}: ${row.title_es.slice(0, 55)} ---`)')
a('')
a('    if (existingIds.has(eid)) {')
a('      console.log("  SKIP -- ya existe en DB")')
a('      results.push({ external_id: eid, status: "skip_exists", reason: "ya existe" })')
a('      countExists++')
a('      continue')
a('    }')
a('')
a('    const allFolders = fs.readdirSync(FOTOS_BASE)')
a('    const folder     = allFolders.find(f => f.startsWith(eid + "_"))')
a('')
a('    if (!folder) {')
a('      console.log("  SKIP -- sin carpeta de fotos")')
a('      results.push({ external_id: eid, status: "skip_no_photos", reason: "sin carpeta" })')
a('      countNoPhotos++')
a('      continue')
a('    }')
a('')
a('    const folderPath = path.join(FOTOS_BASE, folder)')
a('    const imgFiles   = fs.readdirSync(folderPath)')
a('      .filter(f => /\\.(jpe?g|png|webp)$/i.test(f))')
a('      .sort()')
a('')
a('    if (imgFiles.length === 0) {')
a('      console.log("  SKIP -- carpeta vacia")')
a('      results.push({ external_id: eid, status: "skip_no_photos", reason: `carpeta vacia: ${folder}` })')
a('      countNoPhotos++')
a('      continue')
a('    }')
a('')
a('    console.log(`  Subiendo ${imgFiles.length} fotos...`)')
a('    const uploadedUrls: string[] = []')
a('    for (let i = 0; i < imgFiles.length; i++) {')
a('      const fp = path.join(folderPath, imgFiles[i])')
a('      process.stdout.write(`    [${String(i + 1).padStart(2, "0")}/${imgFiles.length}] ${imgFiles[i]} ... `)')
a('      const url = await uploadPhoto(fp)')
a('      uploadedUrls.push(url)')
a('      console.log("OK")')
a('    }')
a('')
a('    const slug = generateSlug(row.title_es)')
a('    console.log(`  INSERT slug=${slug}`)')
a('')
a('    const { error: ie } = await supabase.from("properties").insert({')
a('      title:           row.title_es,')
a('      slug,')
a('      property_type:   row.property_type || null,')
a('      price:           row.price ? Number(row.price) : null,')
a('      currency:        "USD",')
a('      location:        row.location || null,')
a('      province:        null,')
a('      country:         "Indonesia",')
a('      bedrooms:        row.bedrooms  ? parseInt(row.bedrooms,  10) : null,')
a('      bathrooms:       row.bathrooms ? parseInt(row.bathrooms, 10) : null,')
a('      area_sqm:        row.area_sqm  ? Number(row.area_sqm)       : null,')
a('      description:     row.descripcion_es || null,')
a('      external_source: "prestige-bali",')
a('      external_id:     eid,')
a('      status:          "active",')
a('      hidden:          false,')
a('      sold:            false,')
a('      featured:        false,')
a('      classification:  null,')
a('      is_development:  false,')
a('      image_url:       uploadedUrls[0] ?? null,')
a('      gallery_urls:    uploadedUrls,')
a('    })')
a('')
a('    if (ie) {')
a('      console.error(`  ERROR INSERT: ${ie.message}`)')
a('      results.push({ external_id: eid, status: "error", reason: ie.message })')
a('      continue')
a('    }')
a('')
a('    const { data: ins } = await supabase')
a('      .from("properties")')
a('      .select("id, ref_code, slug, image_url, gallery_urls")')
a('      .eq("external_id", eid)')
a('      .single()')
a('')
a('    const gc = Array.isArray(ins?.gallery_urls) ? (ins.gallery_urls as string[]).length : 0')
a('    console.log(`  OK -> ref_code=${ins?.ref_code}  fotos=${gc}`)')
a('    if (ins?.ref_code) okRefCodes.push(ins.ref_code)')
a('')
a('    results.push({')
a('      external_id: eid, status: "ok", id: ins?.id,')
a('      ref_code: ins?.ref_code, slug: ins?.slug,')
a('      gallery_urls_count: gc, image_url: ins?.image_url,')
a('    })')
a('    countOk++')
a('  }')
a('')
a('  const sorted = [...okRefCodes].sort()')
a('  console.log("\\n================================================")')
a('  console.log("  RESUMEN")')
a('  console.log("================================================")')
a('  console.log(`  Insertadas OK:    ${countOk}`)')
a('  console.log(`  Skip ya-existe:   ${countExists}`)')
a('  console.log(`  Skip sin-fotos:   ${countNoPhotos}`)')
a('  const noP = results.filter(r => r.status === "skip_no_photos")')
a('  if (noP.length > 0) {')
a('    console.log("  Sin fotos (listado):")')
a('    noP.forEach(r => console.log(`    ${r.external_id} -- ${r.reason}`))')
a('  }')
a('  if (sorted.length > 0) {')
a('    console.log(`  ref_codes: ${sorted[0]} .. ${sorted[sorted.length - 1]} (${sorted.length} asignados)`)')
a('  }')
a('')
a('  let log: unknown[] = []')
a('  if (fs.existsSync(LOG_PATH)) {')
a('    try { const p = JSON.parse(fs.readFileSync(LOG_PATH, "utf-8")); log = Array.isArray(p) ? p : [p] }')
a('    catch { log = [] }')
a('  }')
a('  log.push({')
a('    run: "FASE-4.N-P7",')
a('    timestamp: new Date().toISOString(),')
a('    summary: {')
a('      total_csv: rows.length,')
a('      inserted: countOk,')
a('      skip_exists: countExists,')
a('      skip_no_photos: countNoPhotos,')
a('      ref_codes_range: sorted.length > 0')
a('        ? { from: sorted[0], to: sorted[sorted.length - 1] }')
a('        : null,')
a('    },')
a('    detail: results,')
a('  })')
a('  fs.writeFileSync(LOG_PATH, JSON.stringify(log, null, 2))')
a('  console.log(`\\nLog => ${LOG_PATH}`)')
a('  console.log("CARGA COMPLETADA")')
a('}')
a('')
a('main().catch(err => { console.error(err); process.exit(1) })')

content = '\n'.join(lines) + '\n'
out = r'C:\Users\Asus\Desktop\proyecto\assets-golden-next\scripts\loadBaliAll.ts'
with open(out, 'w', encoding='utf-8') as f:
    f.write(content)
print('OK bytes=' + str(os.path.getsize(out)))
